const imageFilenames = {
    turtle: 'turtle.jpg',
    tired: 'tired.jpg',
    swim: 'swim.jpg',
    surprised: 'surprised.jpg',
    stew: 'stew.jpg',
    squid: 'squid.jpg',
    smile: 'smile.jpg',
    skirt: 'skirt.jpg',
    skip: 'skip.jpg',
    sister: 'sister.jpg',
    sing: 'sing.jpg',
    shoe: 'shoe.jpg',
    shirt: 'shirt.jpg',
    sheep: 'sheep.jpg',
    scared: 'scared.jpg',
    sad: 'sad.jpg',
    run: 'run.jpg',
    ride: 'ride.jpg',
    recipe: 'recipe.jpg',
    rabbit: 'rabbit.jpg',
    point: 'point.jpg',
    play: 'play.jpg',
    pig: 'pig.jpg',
    pet: 'pet.jpg',
    pants: 'pants.jpg',
    open: 'open.jpg',
    mushroom: 'mushroom.jpg',
    mouse: 'mouse.jpg',
    mother: 'mother.jpg',
    lion: 'lion.jpg',
    laugh: 'laugh.jpg',
    jump: 'jump.jpg',
    hug: 'hug.jpg',
    horse: 'horse.jpg',
    happy: 'happy.jpg',
    grandpa: 'grandpa.jpg',
    grandma: 'grandma.jpg',
    giraffe: 'giraffe.jpg',
    garlic: 'garlic.jpg',
    frog: 'frog.jpg',
    Food: 'Food.jpg',
    fly: 'fly.jpg',
    fish1: 'fish1.jpg',
    fish: 'fish.jpg',
    father: 'father.jpg',
    Family: 'Family.jpg',
    fail: 'fail.png',
    excellent: 'excellent.png',
    emotions: 'Emotions.jpg',
    dress: 'dress.jpg',
    draw: 'draw.jpg',
    dolphin: 'dolphin.jpg',
    dog: 'dog.jpg',
    dive: 'dive.jpg',
    dance: 'dance.jpg',
    cry: 'cry.jpg',
    courgette: 'courgette.jpg',
    coat: 'coat.jpg',
    Clothes: 'Clothes.jpg',
    chicken: 'chicken.jpg',
    chick: 'chick.jpg',
    cereal: 'cereal.jpg',
    cat: 'cat.jpg',
    brother: 'brother.jpg',
    boot: 'boot.jpg',
    blouse: 'blouse.jpg',
    bird: 'bird.jpg',
    aubergine: 'aubergine.jpg',
    animalB: 'Animal (set B).jpg',
    animalA: 'Animal (set A).jpg',
    angry: 'angry.jpg',
    actionB: 'Action (set B).jpg',
    actionA: 'Action (set A).jpg',
}

function resolve(filename) {
    return require(`../img/${filename}`);
}

export const categories = [
    {
        name: 'Action (set A)',
        filename: resolve(imageFilenames.actionA),
        cards: [
            {
                word: "cry",
                translation: "плакать",
                filename: resolve(imageFilenames.cry),
                audioSrc: "audio/cry.mp3",
            },
            {
                word: "dance",
                translation: "танцевать",
                filename: resolve(imageFilenames.dance),
                audioSrc: "audio/dance.mp3",
            },
            {
                word: "dive",
                translation: "нырять",
                filename: resolve(imageFilenames.dive),
                audioSrc: "audio/dive.mp3",
            },
            {
                word: "draw",
                translation: "рисовать",
                filename: resolve(imageFilenames.draw),
                audioSrc: "audio/draw.mp3",
            },
            {
                word: "fishing",
                translation: "ловить рыбу",
                filename: resolve(imageFilenames.fish),
                audioSrc: "audio/fish.mp3",
            },
            {
                word: "fly",
                translation: "летать",
                filename: resolve(imageFilenames.fly),
                audioSrc: "audio/fly.mp3",
            },
            {
                word: "hug",
                translation: "обнимать",
                filename: resolve(imageFilenames.hug),
                audioSrc: "audio/hug.mp3",
            },
            {
                word: "jump",
                translation: "прыгать",
                filename: resolve(imageFilenames.jump),
                audioSrc: "audio/jump.mp3",
            },
        ],
    },
    {
        name: 'Action (set B)',
        filename: resolve(imageFilenames.actionB),
        cards: [
            {
                word: "open",
                translation: "открывать",
                filename: resolve(imageFilenames.open),
                audioSrc: "audio/open.mp3",
            },
            {
                word: "play",
                translation: "играть",
                filename: resolve(imageFilenames.play),
                audioSrc: "audio/play.mp3",
            },
            {
                word: "point",
                translation: "указывать",
                filename: resolve(imageFilenames.point),
                audioSrc: "audio/point.mp3",
            },
            {
                word: "ride",
                translation: "ездить",
                filename: resolve(imageFilenames.ride),
                audioSrc: "audio/ride.mp3",
            },
            {
                word: "run",
                translation: "бегать",
                filename: resolve(imageFilenames.run),
                audioSrc: "audio/run.mp3",
            },
            {
                word: "sing",
                translation: "петь",
                filename: resolve(imageFilenames.sing),
                audioSrc: "audio/sing.mp3",
            },
            {
                word: "skip",
                translation: "пропускать, прыгать",
                filename: resolve(imageFilenames.skip),
                audioSrc: "audio/skip.mp3",
            },
            {
                word: "swim",
                translation: "плавать",
                filename: resolve(imageFilenames.swim),
                audioSrc: "audio/swim.mp3",
            },
        ],
    },
    {
        name: 'Animal (set A)',
        filename: resolve(imageFilenames.animalA),
        cards: [
            {
                word: "cat",
                translation: "кот",
                filename: resolve(imageFilenames.cat),
                audioSrc: "audio/cat.mp3",
            },
            {
                word: "chick",
                translation: "цыплёнок",
                filename: resolve(imageFilenames.chick),
                audioSrc: "audio/chick.mp3",
            },
            {
                word: "chicken",
                translation: "курица",
                filename: resolve(imageFilenames.chicken),
                audioSrc: "audio/chicken.mp3",
            },
            {
                word: "dog",
                translation: "собака",
                filename: resolve(imageFilenames.dog),
                audioSrc: "audio/dog.mp3",
            },
            {
                word: "horse",
                translation: "лошадь",
                filename: resolve(imageFilenames.horse),
                audioSrc: "audio/horse.mp3",
            },
            {
                word: "pig",
                translation: "свинья",
                filename: resolve(imageFilenames.pig),
                audioSrc: "audio/pig.mp3",
            },
            {
                word: "rabbit",
                translation: "кролик",
                filename: resolve(imageFilenames.rabbit),
                audioSrc: "audio/rabbit.mp3",
            },
            {
                word: "sheep",
                translation: "овца",
                filename: resolve(imageFilenames.sheep),
                audioSrc: "audio/sheep.mp3",
            },
        ],
    },
    {
        name: 'Animal (set B)',
        filename: resolve(imageFilenames.actionB),
        cards: [
            {
                word: "bird",
                translation: "птица",
                filename: resolve(imageFilenames.bird),
                audioSrc: "audio/bird.mp3",
            },
            {
                word: "fish",
                translation: "рыба",
                image: resolve(imageFilenames.fish1),
                audioSrc: "audio/fish.mp3",
            },
            {
                word: "frog",
                translation: "жаба",
                filename: resolve(imageFilenames.frog),
                audioSrc: "audio/frog.mp3",
            },
            {
                word: "giraffe",
                translation: "жирафа",
                filename: resolve(imageFilenames.giraffe),
                audioSrc: "audio/giraffe.mp3",
            },
            {
                word: "lion",
                translation: "лев",
                filename: resolve(imageFilenames.lion),
                audioSrc: "audio/lion.mp3",
            },
            {
                word: "mouse",
                translation: "мышь",
                filename: resolve(imageFilenames.mouse),
                audioSrc: "audio/mouse.mp3",
            },
            {
                word: "turtle",
                translation: "черепаха",
                filename: resolve(imageFilenames.turtle),
                audioSrc: "audio/turtle.mp3",
            },
            {
                word: "dolphin",
                translation: "дельфин",
                filename: resolve(imageFilenames.dolphin),
                audioSrc: "audio/dolphin.mp3",
            },
        ],
    },
    {
        name: 'Clothes',
        filename: resolve(imageFilenames.Clothes),
        cards: [
            {
                word: "skirt",
                translation: "юбка",
                filename: resolve(imageFilenames.skirt),
                audioSrc: "audio/skirt.mp3",
            },
            {
                word: "pants",
                translation: "брюки",
                filename: resolve(imageFilenames.pants),
                audioSrc: "audio/pants.mp3",
            },
            {
                word: "blouse",
                translation: "блузка",
                filename: resolve(imageFilenames.blouse),
                audioSrc: "audio/blouse.mp3",
            },
            {
                word: "dress",
                translation: "платье",
                filename: resolve(imageFilenames.dress),
                audioSrc: "audio/dress.mp3",
            },
            {
                word: "boot",
                translation: "ботинок",
                filename: resolve(imageFilenames.boot),
                audioSrc: "audio/boot.mp3",
            },
            {
                word: "shirt",
                translation: "рубашка",
                filename: resolve(imageFilenames.shirt),
                audioSrc: "audio/shirt.mp3",
            },
            {
                word: "coat",
                translation: "пальто",
                filename: resolve(imageFilenames.coat),
                audioSrc: "audio/coat.mp3",
            },
            {
                word: "shoe",
                translation: "туфли",
                filename: resolve(imageFilenames.shoe),
                audioSrc: "audio/shoe.mp3",
            },
        ],
    },
    {
        name: 'Emotions',
        filename: resolve(imageFilenames.emotions),
        cards: [
            {
                word: "sad",
                translation: "грустный",
                filename: resolve(imageFilenames.sad),
                audioSrc: "audio/sad.mp3",
            },
            {
                word: "angry",
                translation: "сердитый",
                filename: resolve(imageFilenames.angry),
                audioSrc: "audio/angry.mp3",
            },
            {
                word: "happy",
                translation: "счастливый",
                filename: resolve(imageFilenames.happy),
                audioSrc: "audio/happy.mp3",
            },
            {
                word: "tired",
                translation: "уставший",
                filename: resolve(imageFilenames.tired),
                audioSrc: "audio/tired.mp3",
            },
            {
                word: "surprised",
                translation: "удивлённый",
                filename: resolve(imageFilenames.surprised),
                audioSrc: "audio/surprised.mp3",
            },
            {
                word: "scared",
                translation: "испуганный",
                filename: resolve(imageFilenames.scared),
                audioSrc: "audio/scared.mp3",
            },
            {
                word: "smile",
                translation: "улыбка",
                filename: resolve(imageFilenames.smile),
                audioSrc: "audio/smile.mp3",
            },
            {
                word: "laugh",
                translation: "смех",
                filename: resolve(imageFilenames.laugh),
                audioSrc: "audio/laugh.mp3",
            },
        ],
    },
    {
        name: 'Food',
        filename: resolve(imageFilenames.Food),
        cards: [
            {
                word: "squid",
                translation: "кальмар",
                filename: resolve(imageFilenames.squid),
                audioSrc: "audio/squid.mp3",
            },
            {
                word: "courgette",
                translation: "кабачок",
                filename: resolve(imageFilenames.courgette),
                audioSrc: "audio/courgette.mp3",
            },
            {
                word: "garlic",
                translation: "чеснок",
                filename: resolve(imageFilenames.garlic),
                audioSrc: "audio/garlic.mp3",
            },
            {
                word: "mushroom",
                translation: "гриб",
                filename: resolve(imageFilenames.mushroom),
                audioSrc: "audio/mushroom.mp3",
            },
            {
                word: "cereal",
                translation: "зерновой",
                filename: resolve(imageFilenames.cereal),
                audioSrc: "audio/cereal.mp3",
            },
            {
                word: "aubergine",
                translation: "баклажан",
                filename: resolve(imageFilenames.aubergine),
                audioSrc: "audio/aubergine.mp3",
            },
            {
                word: "stew",
                translation: "тушенка",
                filename: resolve(imageFilenames.stew),
                audioSrc: "audio/stew.mp3",
            },
            {
                word: "recipe",
                translation: "рецепт",
                filename: resolve(imageFilenames.recipe),
                audioSrc: "audio/recipe.mp3",
            },
        ],
    },
    {
        name: 'Family',
        filename: resolve(imageFilenames.Family),
        cards: [
            {
                word: "family",
                translation: "семья",
                filename: resolve(imageFilenames.Family),
                audioSrc: "audio/family.mp3",
            },
            {
                word: "mother",
                translation: "мать",
                filename: resolve(imageFilenames.mother),
                audioSrc: "audio/mother.mp3",
            },
            {
                word: "father",
                translation: "отец",
                filename: resolve(imageFilenames.father),
                audioSrc: "audio/father.mp3",
            },
            {
                word: "sister",
                translation: "сестра",
                filename: resolve(imageFilenames.sister),
                audioSrc: "audio/sister.mp3",
            },
            {
                word: "brother",
                translation: "брат",
                filename: resolve(imageFilenames.brother),
                audioSrc: "audio/brother.mp3",
            },
            {
                word: "grandma",
                translation: "бабушка",
                filename: resolve(imageFilenames.grandma),
                audioSrc: "audio/grandma.mp3",
            },
            {
                word: "grandpa",
                translation: "дедушка",
                filename: resolve(imageFilenames.grandpa),
                audioSrc: "audio/grandpa.mp3",
            },
            {
                word: "pet",
                translation: "домашнее животное",
                filename: resolve(imageFilenames.pet),
                audioSrc: "audio/pet.mp3",
            },
        ],
    },
];
